// AUTO-GENERATED by protoc-gen-webviewrpc
import { HelloRequest,HelloResponse, } from "./hello_service.pb.js";
// ↑ 실제 JS 메시지 생성 로직( --js_out )으로 만들어진 모듈을 import 한다 가정

export class HelloServiceClient {
  constructor(rpcClient) {
    this.rpcClient = rpcClient;
  }

  
  async SayHello(request) {
    // request -> protobuf encode -> base64 -> send
    const reqBytes = myapp.HelloRequest.encode(request).finish();
    const respBytes = await this.rpcClient.callMethod(
      "HelloService.SayHello",
      reqBytes
    );
    return myapp.HelloResponse.decode(respBytes);
  }
  
  async SayGoodbye(request) {
    // request -> protobuf encode -> base64 -> send
    const reqBytes = myapp.HelloRequest.encode(request).finish();
    const respBytes = await this.rpcClient.callMethod(
      "HelloService.SayGoodbye",
      reqBytes
    );
    return myapp.HelloResponse.decode(respBytes);
  }
  
}