// AUTO-GENERATED by protoc-gen-webviewrpc
using System.Threading.Tasks;
using Google.Protobuf;

namespace Myapp
{
    public class HelloServiceClient
    {
        private readonly IWebViewRpcClient _rpcClient;

        public HelloServiceClient(IWebViewRpcClient rpcClient)
        {
            _rpcClient = rpcClient;
        }

        
        public async Task<myapp.HelloResponse> SayHello(myapp.HelloRequest request)
        {
            return await _rpcClient.CallMethodAsync<myapp.HelloResponse>("HelloService.SayHello", request);
        }
        
        public async Task<myapp.HelloResponse> SayGoodbye(myapp.HelloRequest request)
        {
            return await _rpcClient.CallMethodAsync<myapp.HelloResponse>("HelloService.SayGoodbye", request);
        }
        
    }
}